const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

const SEAT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  BOOKED: 'BOOKED'
};

const BOOKING_STATUS = {
  RESERVED: 'RESERVED',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

const TRANSACTION_TYPE = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
  REFUND: 'REFUND'
};

module.exports = {
  ROLES,
  SEAT_STATUS,
  BOOKING_STATUS,
  TRANSACTION_TYPE
};
